name: test_me_poupe
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  flutter_modular: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-ExtraLight.otf
           weight: 100
         - asset: assets/fonts/Poppins-Thin.otf
           weight: 200
         - asset: assets/fonts/Poppins-Light.otf
           weight: 300          
         - asset: assets/fonts/Poppins-Regular.otf          
           weight: 400
         - asset: assets/fonts/Poppins-Medium.otf          
           weight: 500
         - asset: assets/fonts/Poppins-SemiBold.otf          
           weight: 600
         - asset: assets/fonts/Poppins-Bold.otf
           weight: 700
         - asset: assets/fonts/Poppins-Black.otf
           weight: 800
         - asset: assets/fonts/Poppins-ExtraBold.otf
           weight: 900
     